---
title: "People Based ML - Housing Repair Tax Credit"
author: "Johnathan Clementi"
date: "11/2/2021"
output: 
  html_document:
    theme: journal
    highlight: haddock
    toc: true
    toc_float:
      collapsed: true
      smooth_scroll: true
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=TRUE, message=FALSE, warning=FALSE)

library(caret)
library(FNN)
library(ggcorrplot)
library(grid)
library(gridExtra)
library(htmltools)
library(kableExtra)
library(knitr)
library(lubridate)
library(plotROC)
library(pROC)
library(pscl)
library(sf)
library(spatstat)
library(spdep)
library(tidycensus)
library(tidyverse)
library(viridis)


options(scipen =  "sf")
options(scipen = 999)

# functions
root.dir = "https://raw.githubusercontent.com/urbanSpatial/Public-Policy-Analytics-Landing/master/DATA/"
source("https://raw.githubusercontent.com/urbanSpatial/Public-Policy-Analytics-Landing/master/functions.r")

palette5 <- c("#981FAC","#CB0F8B","#FF006A","#FE4C35","#FE9900")
palette4 <- c("#981FAC","#FF006A","#FE4C35","#FE9900")
palette2 <- c("#981FAC","#FF006A")
```

# Introduction

Data Dictionary:
```{r}
dataDictionary <- read.csv("dataDictionary.csv")

# dataDictionary %>%
#   kable()

```

## Data
```{r}
housingSubsidy <- read.csv(paste0(root.dir,"Chapter6/housingSubsidy.csv"))

housingSubsidy <- housingSubsidy %>%
  rename(# Individual characteristics
          indv.age = age,
          indv.job = job,
          indv.marital = marital,
          indv.education = education,
          indv.taxBillInPHL = taxbill_in_phl,
          # House characteristics
          house.taxLien = taxLien,
          house.mortgage = mortgage,
          house.spentOnRepairs = spent_on_repairs,
          # Characteristics of the campaigns
          campaign.contact = contact,
          campaign.month = month,
          campaign.dayOfWk = day_of_week,
          campaign.numContacts = campaign,
          campaign.numDaysPC = pdays,
          campaign.prevContact = previous,
          campaign.prevOutcome = poutcome,
          # Economic environment factors
          env.unemploymentRate = unemploy_rate,
          env.consPriceIdx = cons.price.idx,
          env.consConfIdx = cons.conf.idx,
          env.inflationRate = inflation_rate,
        ) 
```

### Exploration
```{r}
housingSubsidy %>%
  dplyr::select(y, house.spentOnRepairs,env.consPriceIdx, env.consConfIdx, campaign.numContacts, campaign.numDaysPC, indv.age) %>%
  gather(Variable, value, -y) %>%
    ggplot(aes(y, value, fill=y)) + 
      geom_bar(position = "dodge", stat = "summary", fun.y = "mean") + 
      facet_wrap(~Variable, scales = "free") +
      scale_fill_manual(values = palette2) +
      labs(x="y", y="Value", 
           title = "Feature associations with the likelihood of deployment of credit",
           subtitle = "(continous outcomes)") +
      theme(legend.position = "none")

housingSubsidy %>%
    dplyr::select(y, house.spentOnRepairs,env.consPriceIdx, env.consConfIdx, campaign.numContacts, campaign.numDaysPC, indv.age) %>%
    gather(Variable, value, -y) %>%
    ggplot() + 
    geom_density(aes(value, color=y), fill = "transparent") + 
    facet_wrap(~Variable, scales = "free") +
    scale_fill_manual(values = palette2) +
    labs(title = "Feature distributions took credit vs. no credit",
         subtitle = "(continous outcomes)") 
```
```{r fig.width=10, fig.height= 10}
housingSubsidy %>%
  dplyr::select(y, indv.job, indv.marital, indv.education, campaign.contact, campaign.month, campaign.dayOfWk, house.mortgage, house.taxLien) %>%
  gather(Variable, value, -y) %>%
  count(Variable, value, y) %>%
  ggplot(aes(value, n, fill = y)) +   
    geom_bar(position = "fill", stat="identity") +
    facet_wrap(~Variable, scales="free") +
    scale_fill_manual(values = palette2) +
    labs(x="Churn", y="Count",
         title = "Feature associations with the likelihood of churn",
         subtitle = "Three category features") +
    plotTheme() + theme(axis.text.x = element_text(angle = 45, hjust = 1))

# Campaign month share
#table(housingSubsidy$campaign.month)
#round(table(housingSubsidy$campaign.month)/sum(table(housingSubsidy$campaign.month)),2)
```

```{r correlationMatrix}
numericVars <- housingSubsidy %>% 
  select(where(is.numeric)) %>%
  select(-X) %>%
  na.omit()


ggcorrplot(
  round(cor(numericVars), 1), 
  p.mat = cor_pmat(numericVars),
  colors = c("#FA7800", "white", "#25CB10"),
  type="lower",
  insig = "blank") +  
    labs(title = "Correlation across numeric variables")


#trying to find variables that have a correlation value between 0.5 and -0.5
res <- as.data.frame(cor(numericVars)) %>%
  rownames_to_column()

#pivot longer and sort through list 
posCor <- res %>%
  select(!c("house.spentOnRepairs","y_numeric")) %>%
  pivot_longer(2:(ncol(res)-2)) %>%
  group_by(value) %>%
  arrange(desc(value)) %>%
  filter(value >= 0.1 & value <=0.6)

  

negCor <- res %>%
  select(!c("house.spentOnRepairs","y_numeric")) %>%
  pivot_longer(2:(ncol(res)-2)) %>%
  group_by(value) %>%
  arrange(desc(value)) %>%
  filter(value >= -0.6 & value <= -0.1)

corlist <- bind_rows(posCor,negCor)

corlist <- corlist %>%
  group_by(value) %>%
  arrange(desc(value))

#all odd numbers between 1 and 80
# Removes duplicates pairs that come from correlation matrix
keep <- c(1:nrow(corlist))
keep <- which(keep %% 2 == 1)

corlist <- corlist %>%
             slice(keep)

# includes all variables correlated with y_numeric
ynumCorlist <- corlist %>%
  filter(rowname == "y_numeric")

keep <- ynumCorlist$name

# categorical <- colnames(studentData %>%
#   select(where(is.factor)) %>%
#     st_drop_geometry())
# 
# 
# categorical <- c("Zip","District","price")
# keep <- append(keep, categorical)
```

### Engineering Features
```{r}
  
# # Identifying which variales to transform:
# yes <- housingSubsidy %>% filter(y_numeric == 1)
# 
# #Number of contacts for current campaign
# table(yes$campaign.numContacts)
# table(housingSubsidy$campaign.numContacts)
# # Most indv taking subsidy were contacted 5 or less times
# 
# # Age of indv
# table(yes$indv.age)
# table(housingSubsidy$indv.age)
# # Most indv taking subsidy were between 25 and 60
# 
# # Indv education
# temp <- housingSubsidy %>% filter(indv.education != "illiterate")
# table(temp$indv.education)
# table(yes$indv.education)/table(temp$indv.education)
# # People with HS degree or higher had at least a 10% chance of taking the subsidy
# 
# # Previous Outcome
# temp <- housingSubsidy %>% mutate(campaign.prevOutcome = case_when(campaign.prevOutcome == "failure" ~ 0,
#                                      campaign.prevOutcome == "nonexistent" ~ 0,
#                                      campaign.prevOutcome == "success" ~ 1
#                                      ))
# yes <- yes %>% mutate(campaign.prevOutcome = case_when(campaign.prevOutcome == "failure" ~ 0,
#                                      campaign.prevOutcome == "nonexistent" ~ 0,
#                                      campaign.prevOutcome == "success" ~ 1
#                                      ))
# table(yes$campaign.prevOutcome)
# table(temp$campaign.prevOutcome)
# table(yes$campaign.prevOutcome)/table(temp$campaign.prevOutcome)
# # People that took the subsidy previously are 64% likely to take the subsidy again


# Engineer Features based on findings from code above
housingSubsidy <- housingSubsidy %>%
  mutate(eng.indv.job = indv.job) %>%# For engineered Features
  mutate(eng.indv.marital = case_when(indv.marital == "divorced" ~ "notMarried",
                                  indv.marital == "single" ~ "notMarried",
                                  indv.marital == "unknown" ~ "unknown",
                                  indv.marital == "married" ~ "married"
                                  )
         ) %>%
  mutate(eng.indv.job = replace(eng.indv.job, eng.indv.job == "housemaid", "services"),
         eng.indv.job = replace(eng.indv.job, eng.indv.job == "self-employed", "entrepreneur"),
         eng.indv.job = replace(eng.indv.job, eng.indv.job == "retired", "notWorking"),
         eng.indv.job = replace(eng.indv.job, eng.indv.job == "student", "notWorking"),
         eng.indv.job = replace(eng.indv.job, eng.indv.job == "unemployed", "notWorking"),
         eng.indv.job = replace(eng.indv.job, eng.indv.job == "admin.", "admin")
        ) %>%
  mutate(eng.indv.edu = case_when(indv.education == "illiterate" ~ "BelowHS",
                                    indv.education == "basic.4y" ~ "BelowHS",
                                    indv.education == "basic.6y" ~ "BelowHS",
                                    indv.education == "basic.9y" ~ "BelowHS",
                                    indv.education == "high.school" ~ "HS_andAbove",
                                    indv.education == "professional.course" ~ "HS_andAbove",
                                    indv.education == "university.degree" ~ "HS_andAbove",
                                    indv.education == "unknown" ~ "unknown"
                                    )
         ) %>%
  mutate(eng.campaign.dayMonth = paste0(campaign.dayOfWk, "_", campaign.month),
         eng.5orLessContacts = case_when(campaign.numContacts < 6 ~ 1,
                                           campaign.numContacts > 5 ~ 0
                                           ),
         eng.indv.age = case_when(indv.age > 24 && indv.age < 61 ~ 1,
                             indv.age < 25 ~ 0,
                             indv.age > 60 ~ 0),
         eng.numContact = case_when(campaign.numContacts < 6 ~ 1,
                                    campaign.numContacts > 5 ~ 0
                                    ),
         eng.prevOutcome = case_when(campaign.prevOutcome == "failure" ~ 0,
                                     campaign.prevOutcome == "nonexistent" ~ 0,
                                     campaign.prevOutcome == "success" ~ 1
                                     )
         )

```

# Methods

### Training and Test Sets
```{r}
set.seed(3456)
trainIndex <- createDataPartition(housingSubsidy$y_numeric, p = .65,
                                  list = FALSE,
                                  times = 1)
creditTrain <- housingSubsidy[ trainIndex,] 
creditTest  <- housingSubsidy[-trainIndex,]
```

### Model Estimation
```{r}
kitchenSink_reg <- glm(y_numeric ~ .,
                  data=creditTrain %>% dplyr::select(-y, -starts_with("eng")),
                  family="binomial" (link="logit"))

summary(kitchenSink_reg)

pR2(kitchenSink_reg)[4]
```
```{r}
testProbs_Ksink <- data.frame(Outcome = as.factor(creditTest$y_numeric),
                        Probs = predict(kitchenSink_reg, creditTest, type= "response"))
#head(testProbs)
```

#### Distributions of Predicted Probabilities
```{r}
ggplot(testProbs_Ksink, aes(x = Probs, fill = as.factor(Outcome))) + 
  geom_density() +
  facet_grid(Outcome ~ .) +
  scale_fill_manual(values = palette2) + xlim(0, 1) +
  labs(x = "Credit", y = "Density of probabilities",
       title = "Distribution of predicted probabilities by observed outcome") +
  plotTheme() + theme(strip.text.x = element_text(size = 18),
        legend.position = "none")
```
#### Confusion Matrix
```{r}
testProbs_Ksink <- testProbs_Ksink %>%
  mutate(predOutcome  = as.factor(ifelse(testProbs_Ksink$Probs > 0.5 , 1, 0)))

#head(testProbs_Ksink)

caret::confusionMatrix(testProbs_Ksink$predOutcome, testProbs_Ksink$Outcome, 
                       positive = "1")
```


# Methods 2 : A honed model

### Model Estimation
```{r}
honedReg <- glm(y_numeric ~ .,
                  data=creditTrain %>% dplyr::select(-y, -campaign.month, -campaign.dayOfWk, -indv.job, -house.taxLien),
                  family="binomial" (link="logit"))

summary(honedReg)

pR2(honedReg)[4]
```
```{r}
testProbs_honed <- data.frame(Outcome = as.factor(creditTest$y_numeric),
                        Probs = predict(honedReg, creditTest, type= "response"))
#head(testProbs_honed)
```

# Comparison

### Distributions of Predicted Probabilities
```{r, fig.height=8, fig.width=10}
grid.arrange(nrow = 2,
  ggplot(testProbs_Ksink, aes(x = Probs, fill = as.factor(Outcome))) + 
  geom_density() +
  facet_grid(Outcome ~ .) +
  scale_fill_manual(values = palette2) + xlim(0, 1) +
  labs(x = "Credit", y = "Density of probabilities",
       title = "Distribution of predicted probabilities by observed outcome\nKitchen Sink model") +
  plotTheme() + theme(strip.text.x = element_text(size = 18),
        legend.position = "none"),
  
  ggplot(testProbs_honed, aes(x = Probs, fill = as.factor(Outcome))) + 
    geom_density() +
    facet_grid(Outcome ~ .) +
    scale_fill_manual(values = palette2) + xlim(0, 1) +
    labs(x = "Credit", y = "Density of probabilities",
         title = "Distribution of predicted probabilities by observed outcome\nHoned Model") +
    plotTheme() + theme(strip.text.x = element_text(size = 18),
          legend.position = "none")
)
```
#### Confusion Matrix
```{r}
testProbs_honed <- testProbs_honed %>%
  mutate(predOutcome  = as.factor(ifelse(testProbs_honed$Probs > 0.5 , 1, 0)))

#head(testProbs_honed)

caret::confusionMatrix(testProbs_honed$predOutcome, testProbs_honed$Outcome, 
                       positive = "1")
```


# Results

# Discussion & Conclusions

# Appendix
### Citations
